# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[(b'Married', b'Married'), (b'Single', b'Single'), (b'Divorced', b'Divorced')], max_length=10, null=True),
        ),
    ]
