# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170804_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(choices=[(b'Hinduism', b'Hinduism'), (b'Christian', b'Christian'), (b'Buddhism', b'Buddhism'), (b'Muslim', b'Muslim'), (b'Sikh', b'Sikh'), (b'Jain', b'Jain')], max_length=20, null=True),
        ),
    ]
