# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qualification',
            field=models.CharField(choices=[(b'Under Graduate', b'Under Graduate'), (b'Graduate', b'Graduate'), (b'Post Graduate', b'Post Graduate')], max_length=30, null=True),
        ),
    ]
