# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
