# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[(b'Hinduism', b'Hinduism'), (b'Christian', b'Christian'), (b'Buddhism', b'Buddhism'), (b'Muslim', b'Muslim'), (b'Sikh', b'Sikh'), (b'Jain', b'Jain')], max_length=20, null=True),
        ),
    ]
