# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatclass',
            name='friends',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatclass',
            name='anything',
            field=models.CharField(default='Can we be Friends?', max_length=100),
        ),
    ]
